#!/bin/bash
cd "/Users/benjamindacy/Desktop/Ben/Buisness Projects/ready set ink/Documents/829git"
echo "=================================================="
echo " Improving EVERYTHING already tagged: adds new"
echo " tags to every set that's been downloaded, and"
echo " scrubs slop (junk/repeats/frame numbers) out of"
echo " art-tags.json as it goes."
echo ""
echo " This only touches sets you've already downloaded."
echo " Brand new sets get skipped here -- use"
echo " 'RUN EVERYTHING (all sets, overnight).command' in"
echo " the Start Tagging folder for those first."
echo ""
echo " Safe to close this window any time -- double click"
echo " again later to keep improving."
echo ""
echo " When this finishes, tell Claude: \"I've improved the"
echo " art tags\" -- it'll check the new tags for slop and"
echo " scope, show you a snapshot, and ask whether to ship"
echo " it to the site."
echo "=================================================="
echo ""
python3 art-tools/run_everything_improve.py --model "gemma4:12b"
echo ""
echo "All done (or stopped). Press Enter to close."
read
