const test=require("node:test"),assert=require("node:assert/strict"),Rules=require("../rules.js"),Model=require("../model.js");
test("10-player Competitive event is 4 Swiss rounds into Top 4",()=>assert.deepEqual(Rules.eventStructure(10,"Competitive"),{players:10,rounds:4,cut:4,suggestedCut:4,official:true,requiredCut:true}));
test("attendance table follows the July 14 2026 rules",()=>{for(const [n,rounds,cut] of [[8,3,0],[9,4,4],[16,4,4],[17,5,8],[32,5,8],[33,6,8],[64,6,8],[65,7,8],[128,7,8],[129,8,8],[226,8,8],[227,9,8]]){const s=Rules.eventStructure(n,"Premier");assert.equal(s.rounds,rounds);assert.equal(s.cut,cut)}});
test("Top Cut is not required for Entry level",()=>{const s=Rules.eventStructure(10,"Entry");assert.equal(s.rounds,4);assert.equal(s.cut,0);assert.equal(s.suggestedCut,4)});
test("Premier scoring and record are automatic",()=>assert.deepEqual(Model.record([{result:"W"},{result:"D"},{result:"L"},{result:"W"}]),{w:2,l:1,d:1,points:7}));
test("official events require at least eight players",()=>assert.equal(Rules.eventStructure(7,"Premier").official,false));
test("Top Cut matches do not change Swiss points",()=>assert.deepEqual(Model.record([{result:"W",stage:"swiss"},{result:"W",stage:"cut"}]),{w:1,l:0,d:0,points:3}));
test("game score must agree with the match result",()=>{assert.equal(Model.validScore("W","2-1-0"),true);assert.equal(Model.validScore("W","1-2-0"),false);assert.equal(Model.validScore("D","0-0-3"),true)});
test("personal analytics group opponents and ink pairs",()=>{const a=Model.analytics([{rounds:[{opponent:"Joe",opponentInks:["Ruby","Amethyst"],result:"W",started:"me"},{opponent:"Joe",opponentInks:["Amethyst","Ruby"],result:"L",started:"opponent"}]}]);assert.equal(a.opponents[0].matches,2);assert.equal(a.inks[0].name,"Amethyst / Ruby")});
test("deck and ink-combo analytics stay distinct",()=>{const events=[{deckName:"Control A",inks:["Ruby","Sapphire"],rounds:[{opponent:"A",result:"W"}]},{deckName:"Control B",inks:["Sapphire","Ruby"],rounds:[{opponent:"B",result:"L"}]}],a=Model.analytics(events);assert.equal(a.decks.length,2);assert.equal(a.combos.length,1);assert.equal(a.combos[0].matches,2)});

const ev=(date,deckName,rounds,extra={})=>({name:`Event ${date}`,date,deckName,inks:[],rounds,createdAt:date,...extra});
const m=(result,inks,extra={})=>({kind:"match",opponent:"Opp",opponentInks:inks,result,stage:"swiss",...extra});
test("win rates count Top Cut wins, match points stay Swiss-only",()=>{const a=Model.analytics([ev("2026-09-01","Amber Steel",[m("W",["Ruby"]),m("L",["Ruby"]),m("W",["Ruby"],{stage:"cut"})])]);const ruby=a.inks.find(x=>x.name==="Ruby");assert.equal(ruby.matches,3);assert.equal(ruby.rate,67);assert.equal(a.overall.w,2);assert.equal(Model.record([m("W",[]),m("W",[],{stage:"cut"})]).points,3)});
test("matchup bingo has 21 cells and only counts wins",()=>{const b=Model.bingo([ev("2026-09-01","D",[m("W",["Steel","Amber"]),m("L",["Ruby"]),m("W",["Amethyst"])])]);assert.equal(b.total,21);assert.equal(b.won,2);assert.ok(b.cells.find(c=>c.name==="Amber / Steel").won);assert.ok(!b.cells.find(c=>c.name==="Ruby").won)});
test("milestones and Dust awards come from the journal, in date order",()=>{const events=[ev("2026-09-08","D",[m("W",["Ruby"]),m("D",["Ruby"]),m("W",["Ruby"])],{placement:"Top 8"}),ev("2026-09-01","D",[m("L",["Steel"])])];const ms=Model.milestones(events);assert.equal(ms.done[0].id,"journal1");assert.equal(ms.done[0].date,"2026-09-01");assert.deepEqual(ms.done.map(x=>x.id).sort(),["firstwin","journal1","topcut","undefeated"]);assert.deepEqual(Model.awardsDue(events),["journal1","firstwin","topcut"]);assert.deepEqual(ms.next,{label:"10 matches logged",have:4,need:10})});
test("prep focuses on the weakest matchups with enough games",()=>{const rounds=[...Array(3)].map(()=>m("L",["Ruby"])).concat([...Array(3)].map(()=>m("W",["Steel"])),[m("L",["Amber"])]);const p=Model.prep([ev("2026-09-01","Deck A",rounds),ev("2026-09-02","Deck B",[m("L",["Steel"])])],"Deck A");assert.deepEqual(p.focus.map(x=>x.name),["Ruby","Steel"]);assert.equal(p.rows.length,3);assert.ok(p.rows.find(x=>x.name==="Amber").low)});
test("trend groups by month",()=>{const t=Model.trend([ev("2026-08-30","D",[m("W",[])]),ev("2026-09-02","D",[m("L",[]),m("W",[])])]);assert.deepEqual(t.map(x=>[x.name,x.matches,x.rate]),[["2026-08",1,100],["2026-09",2,50]])});
