(function(root,factory){const api=factory(root.RSITournamentRules||(typeof require==="function"?require("./rules.js"):null));if(typeof module==="object"&&module.exports)module.exports=api;root.RSIFullTournamentModel=api})(typeof globalThis!=="undefined"?globalThis:this,function(Rules){"use strict";
const num=(v,f=null)=>v===""||v==null?f:Number.isFinite(Number(v))?Number(v):f,pct=v=>{const n=num(v);return n==null?null:Math.max(0,Math.min(100,n))};
function cleanPlayer(p){return {name:String(p&&typeof p==="object"?p.name??"":p??"").trim(),w:Math.max(0,num(p?.w,0)),l:Math.max(0,num(p?.l,0)),d:Math.max(0,num(p?.d,0)),omw:pct(p?.omw??p?.omwPct),gw:pct(p?.gw??p?.gwPct),ogw:pct(p?.ogw??p?.ogwPct)}}
function fromLegacy(e){if(!e||!Array.isArray(e.players)||e.players.every(p=>typeof p==="object"))return e?{...e,players:(e.players||[]).map(cleanPlayer)}:e;const stats=Object.fromEntries(e.players.map(n=>[n,cleanPlayer(n)]));(e.rounds||[]).flat().forEach(m=>{const a=stats[m.p1],b=stats[m.p2];if(!a)return;if(m.bye||m.result==="p1"){a.w++;if(b)b.l++}else if(m.result==="p2"){a.l++;if(b)b.w++}else if(m.result==="draw"){a.d++;if(b)b.d++}});return {...e,players:Object.values(stats),legacyRounds:e.rounds||[],rounds:undefined,draft:undefined,dropped:undefined}}
function create(input){const players=(input.players||[]).map(cleanPlayer).filter(p=>p.name);return {id:`standings-${Date.now()}`,name:String(input.name||"").trim(),date:input.date||"",location:String(input.location||"").trim(),level:input.level||"Competitive",type:input.type||"Constructed",players,structure:Rules.eventStructure(players.length,input.level||"Competitive"),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}}
function playerStats(e){return (e?.players||[]).map(cleanPlayer).map(p=>({...p,points:p.w*3+p.d})).sort((a,b)=>b.points-a.points||(b.omw??-1)-(a.omw??-1)||(b.gw??-1)-(a.gw??-1)||(b.ogw??-1)-(a.ogw??-1)||a.name.localeCompare(b.name)).map((p,i)=>({...p,rank:i+1}))}
function outlook(e,name){const rows=playerStats(e),p=rows.find(x=>x.name===name)||rows[0],cut=e?.structure?.cut||Rules.eventStructure(rows.length,e?.level||"Competitive").cut||0;if(!p)return {tone:"neutral",label:"Add player records to calculate an outlook",detail:"Enter the current standings, then calculate again.",cut};if(!cut)return {tone:"neutral",label:"No required Top Cut for this event",detail:"The snapshot is still ranked by match points and any tiebreakers entered.",cut,player:p};const tied=rows.filter(x=>x.points===p.points),above=rows.filter(x=>x.points>p.points).length,best=above+1,worst=above+tied.length;if(worst<=cut)return {tone:"good",label:`${p.name} is currently above the Top ${cut} line`,detail:`Ranked #${p.rank} with ${p.points} match points. The full points tie is inside the cut.`,cut,player:p};if(best<=cut)return {tone:"watch",label:`${p.name} is on the Top ${cut} bubble`,detail:`Ranked #${p.rank} with ${p.points} match points. Tiebreakers decide who lands above the line.`,cut,player:p};return {tone:"warn",label:`${p.name} is currently below the Top ${cut} line`,detail:`Ranked #${p.rank} with ${p.points} match points. Future results can still change the picture.`,cut,player:p}}
function nextResults(e,name){const p=playerStats(e).find(x=>x.name===name);return p?[{label:"Win next round",points:p.points+3},{label:"Draw next round",points:p.points+1},{label:"Lose next round",points:p.points}]:[]}
return {create,cleanPlayer,fromLegacy,playerStats,outlook,nextResults};});
