(function(root,factory){const api=factory(root.RSITournamentRules||(typeof require==="function"?require("./rules.js"):null));if(typeof module==="object"&&module.exports)module.exports=api;root.RSITournamentModel=api})(typeof globalThis!=="undefined"?globalThis:this,function(Rules){
  "use strict";
  const KEY="rsi:tournament-companion:v1";
  const empty=()=>({version:2,active:null,events:[],reminders:[],activeFull:null,fullEvents:[]});
  const normalize=data=>({...empty(),...(data||{}),events:(data&&data.events)||[],reminders:(data&&data.reminders)||[],fullEvents:(data&&data.fullEvents)||[],activeFull:data&&data.activeFull?{workflow:"live",matchFormat:"bo3",roundMinutes:50,dropped:[],audit:[],...data.activeFull}:null});
  function record(rounds){return (rounds||[]).filter(r=>r.stage!=="cut").reduce((a,r)=>{if(r.result==="W")a.w++;if(r.result==="L")a.l++;if(r.result==="D")a.d++;a.points+=Rules.points(r.result);return a},{w:0,l:0,d:0,points:0})}
  function status(event){
    const r=record(event.rounds),s=Rules.eventStructure(event.players,event.level),done=event.rounds.length;
    if(!s.cut)return {tone:"neutral",label:"No required Top Cut",detail:s.suggestedCut?`A Top ${s.suggestedCut} is advised by attendance, but only required for Competitive and Premier events.`:"This attendance has Swiss rounds only."};
    if(done>=s.rounds)return {tone:"neutral",label:"Swiss complete",detail:`Check the official standings for the Top ${s.cut}. Tiebreakers need the full field's results.`};
    const max=r.points+(s.rounds-done)*3;
    if(r.points===done*3)return {tone:"good",label:`On a ${s.cut===4?"Top 4":"Top 8"} pace`,detail:"You are unbeaten so far. Official standings and tiebreakers decide the final cut."};
    if(max<Math.max(3,(s.rounds-1)*3))return {tone:"warn",label:"You may need help",detail:"Keep playing it out. The official standings and tiebreakers are what count."};
    return {tone:"watch",label:"Still in the hunt",detail:"Your next result matters. The official standings and tiebreakers decide the final cut."};
  }
  function create(input){const structure=Rules.eventStructure(input.players,input.level);return {id:`evt-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,name:input.name.trim(),date:input.date,location:(input.location||"").trim(),type:input.type,level:input.level,players:Number(input.players),deckName:input.deckName.trim(),inks:input.inks.slice(0,2),structure,rounds:[],phase:"before",stage:"swiss",createdAt:new Date().toISOString()}}
  function validScore(result,score){if(!score)return true;const [w,l]=score.split("-").map(Number);return result==="W"?w>l:result==="L"?l>w:w===l}
  function group(rounds,key){const map={};rounds.forEach(r=>{const k=key(r);if(!k)return;(map[k]||(map[k]=[])).push(r)});return Object.entries(map).map(([name,items])=>({name,...record(items),matches:items.length,rate:Math.round(record(items).w/items.length*100)})).sort((a,b)=>b.matches-a.matches||b.rate-a.rate)}
  function deckGroups(events,key){const map={};(events||[]).forEach(e=>{const name=key(e);if(!name)return;const item=map[name]||(map[name]={name,rounds:[],events:0,points:0,topCuts:0});const swiss=(e.rounds||[]).filter(r=>r.stage!=="cut");item.rounds.push(...swiss);item.events++;item.points+=record(swiss).points;if((e.rounds||[]).some(r=>r.stage==="cut")||/top\s*(4|8|cut)/i.test(e.placement||""))item.topCuts++});return Object.values(map).map(x=>{const r=record(x.rounds);return {...x,...r,matches:x.rounds.length,rate:x.rounds.length?Math.round(r.w/x.rounds.length*100):0,avgPoints:x.events?Math.round(x.points/x.events*10)/10:0}}).sort((a,b)=>b.matches-a.matches||b.rate-a.rate)}
  function streak(rounds){let n=0,type="";for(let i=rounds.length-1;i>=0;i--){const r=rounds[i].result;if(!type)type=r;if(r!==type)break;n++}return n?`${n} ${type==="W"?"win":type==="L"?"loss":"draw"}${n===1?"":"s"}`:"—"}
  function analytics(events){const rounds=(events||[]).flatMap(e=>(e.rounds||[]).filter(r=>r.kind!=="bye"&&r.opponent)),recent=rounds.slice(-10),opponents=group(rounds,r=>r.opponent),inks=group(rounds,r=>(r.opponentInks||[]).slice().sort().join(" / ")),combos=deckGroups(events,e=>(e.inks||[]).slice().sort().join(" / ")||"No inks recorded"),decks=deckGroups(events,e=>(e.deckName||"").trim()||((e.inks||[]).slice().sort().join(" / ")||"Unnamed deck"));return {overall:record(rounds),opponents,inks,first:group(rounds,r=>r.started==="me"?"Started first":r.started?"Started second":""),choice:group(rounds,r=>r.wonChoice===true?"Won choice":r.wonChoice===false?"Lost choice":""),decks,combos,recent:{...record(recent),matches:recent.length,rate:recent.length?Math.round(record(recent).w/recent.length*100):0},streak:streak(rounds),topCuts:(events||[]).filter(e=>(e.rounds||[]).some(r=>r.stage==="cut")||/top\s*(4|8|cut)/i.test(e.placement||"")).length,bestMatchup:inks.filter(x=>x.matches>=3).sort((a,b)=>b.rate-a.rate)[0]||null,toughestMatchup:inks.filter(x=>x.matches>=3).sort((a,b)=>a.rate-b.rate)[0]||null}}
  function storage(store){return {load(){try{return normalize(JSON.parse(store.getItem(KEY)))}catch(_){return empty()}},save(data){store.setItem(KEY,JSON.stringify(normalize(data)))},key:KEY}}
  return {KEY,empty,normalize,record,status,create,validScore,analytics,storage};
});
