(function(root,factory){const api=factory();if(typeof module==="object"&&module.exports)module.exports=api;root.RSIScreenshotImport=api})(typeof globalThis!=="undefined"?globalThis:this,function(){"use strict";
const LABELS=/^(players?|structure|tournament format|format|category|phase|swiss phase|pairings?|standings?|table|record|rounds?|roster|registered|capacity|event details?|store|location|date|time)$/i;
const MONTHS="january february march april may june july august september october november december".split(" ");
function cleanLines(text){return String(text||"").split(/\r?\n/).map(x=>x.replace(/[|•·]/g," ").replace(/\s+/g," ").trim()).filter(Boolean)}
function afterLabel(lines,names){for(let i=0;i<lines.length;i++){const line=lines[i],lower=line.toLowerCase();for(const name of names){const inline=new RegExp(`^${name}\\s*[:—-]\\s*(.+)$`,"i").exec(line);if(inline?.[1])return inline[1].trim();if(lower===name.toLowerCase()){const next=lines.slice(i+1).find(x=>!LABELS.test(x));if(next)return next}}}return ""}
function isoDate(text){const iso=String(text).match(/\b(20\d{2})[-/]([01]?\d)[-/]([0-3]?\d)\b/);if(iso)return `${iso[1]}-${iso[2].padStart(2,"0")}-${iso[3].padStart(2,"0")}`;const named=String(text).match(new RegExp(`\\b(${MONTHS.join("|")})\\s+(\\d{1,2})(?:st|nd|rd|th)?[,]?\\s+(20\\d{2})\\b`,"i"));if(!named)return "";return `${named[3]}-${String(MONTHS.indexOf(named[1].toLowerCase())+1).padStart(2,"0")}-${named[2].padStart(2,"0")}`}
function likelyNames(lines){const rosterAt=lines.findIndex(x=>/^roster$/i.test(x)),standingsAt=lines.findIndex(x=>/^standings?$/i.test(x)),start=Math.max(rosterAt,standingsAt);if(start<0)return [];const stopWords=/^(pairings?|event details?|tournament format|structure|prizes?|register|check.?in)$/i,seen=new Set();return lines.slice(start+1).filter(line=>{if(stopWords.test(line))return false;if(LABELS.test(line)||/^\d+$/.test(line)||/^(win|loss|draw|complete|registered|checked in)$/i.test(line))return false;if(/\b\d+[-–]\d+(?:[-–]\d+)?\b/.test(line))return false;if(line.length<2||line.length>40)return false;return /[a-z]/i.test(line)&&!seen.has(line)&&seen.add(line)}).slice(0,500)}
function parse(text){const lines=cleanLines(text),joined=lines.join("\n"),round=joined.match(/\bround\s*(\d+)\b/i),count=joined.match(/\bplayers?\s*[:—-]?\s*(\d+)\b/i);let name=afterLabel(lines,["event name","event"]);if(!name){const marker=lines.findIndex(x=>/^event details?$/i.test(x));if(marker>=0)name=lines.slice(marker+1).find(x=>!LABELS.test(x)&&x.length>4)||""}return {name,date:isoDate(joined),store:afterLabel(lines,["store","location"]),format:afterLabel(lines,["tournament format","format"]),round:round?Number(round[1]):null,playerCount:count?Number(count[1]):null,players:likelyNames(lines),rawText:joined}}
return {parse,cleanLines,isoDate};});
