(function(root,factory){const api=factory();if(typeof module==="object"&&module.exports)module.exports=api;root.RSIScreenshotImport=api})(typeof globalThis!=="undefined"?globalThis:this,function(){"use strict";
const LABELS=/^(players?|structure|tournament format|format|category|phase|swiss phase|pairings?|standings?|rank|points?|pts|table|record|rounds?|roster|registered|capacity|event details?|store|location|date|time|omw%?|gw%?|ogw%?)$/i,MONTHS="january february march april may june july august september october november december".split(" ");
function cleanLines(text){return String(text||"").split(/\r?\n/).map(x=>x.replace(/[|•·]/g," ").replace(/\s+/g," ").trim()).filter(Boolean)}
function afterLabel(lines,names){for(let i=0;i<lines.length;i++)for(const name of names){const hit=new RegExp(`^${name}\\s*[:—-]\\s*(.+)$`,"i").exec(lines[i]);if(hit?.[1])return hit[1].trim();if(lines[i].toLowerCase()===name.toLowerCase()){const next=lines.slice(i+1).find(x=>!LABELS.test(x));if(next)return next}}return ""}
function isoDate(text){const iso=String(text).match(/\b(20\d{2})[-/]([01]?\d)[-/]([0-3]?\d)\b/);if(iso)return `${iso[1]}-${iso[2].padStart(2,"0")}-${iso[3].padStart(2,"0")}`;const named=String(text).match(new RegExp(`\\b(${MONTHS.join("|")})\\s+(\\d{1,2})(?:st|nd|rd|th)?[,]?\\s+(20\\d{2})\\b`,"i"));return named?`${named[3]}-${String(MONTHS.indexOf(named[1].toLowerCase())+1).padStart(2,"0")}-${named[2].padStart(2,"0")}`:""}
function parseStanding(line){line=String(line).replace(/^\s*\d+[.)]?\s+/,"").trim();const record=line.match(/\b(\d+)\s*[-–]\s*(\d+)\s*[-–]\s*(\d+)\b/);if(!record)return null;const name=line.slice(0,record.index).replace(/\s+\d+\s*$/," ").trim(),after=line.slice(record.index+record[0].length),perc=[...after.matchAll(/(\d+(?:\.\d+)?)\s*%/g)].map(x=>Number(x[1]));if(!name||LABELS.test(name))return null;return {name,w:+record[1],l:+record[2],d:+record[3],omw:perc[0]??null,gw:perc[1]??null,ogw:perc[2]??null}}
function parseStandings(text){return cleanLines(text).map(parseStanding).filter(Boolean).filter((p,i,a)=>a.findIndex(x=>x.name===p.name)===i)}
function likelyNames(lines){const start=lines.findIndex(x=>/^(standings?|roster)$/i.test(x));if(start<0)return [];return lines.slice(start+1).filter(x=>!LABELS.test(x)&&/[a-z]/i.test(x)&&x.length<50&&!/\d+[-–]\d+[-–]\d+/.test(x)).map(name=>({name,w:0,l:0,d:0,omw:null,gw:null,ogw:null})).slice(0,500)}
function parse(text){const lines=cleanLines(text),joined=lines.join("\n"),round=joined.match(/\bround\s*(\d+)\b/i),count=joined.match(/\bplayers?\s*[:—-]?\s*(\d+)\b/i);let name=afterLabel(lines,["event name","event"]);if(!name){const i=lines.findIndex(x=>/^event details?$/i.test(x));if(i>=0)name=lines.slice(i+1).find(x=>!LABELS.test(x)&&x.length>4)||""}const parsed=parseStandings(joined),standings=parsed.length?parsed:likelyNames(lines);return {name,date:isoDate(joined),store:afterLabel(lines,["store","location"]),format:afterLabel(lines,["tournament format","format"]),round:round?+round[1]:null,playerCount:count?+count[1]:null,standings,players:standings.map(x=>x.name),rawText:joined}}
function formatStanding(p){return `${p.name}, ${p.w}-${p.l}-${p.d}${p.omw==null?"":`, ${p.omw}%, ${p.gw}%, ${p.ogw}%`}`}
return {parse,parseStanding,parseStandings,formatStanding,cleanLines,isoDate};});
